[package]
name = "bacara"
version = "0.1.0"
authors = ["Hadrien G. <knights_of_ni@gmx.com>"]
edition = "2018"
# TODO: Finish filling in more metadata

[dev-dependencies]
genawaiter = "0.2"
rand = "0.7"
require_unsafe_in_body = "0.2"
testbench = "0.7"

[profile.test]
opt-level = 1
